[package]
name = "RapidRAW"
version = "0.0.0"
description = "A blazingly-fast, non-destructive, and GPU-accelerated RAW image editor built with performance in mind."
authors = ["Timon Käch"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "rapidraw_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
tauri = { version = "2.0", features = [ "macos-private-api", "rustls-tls"] }
tauri-plugin-dialog = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
image = "0.25.0"
base64 = "0.22"
tauri-plugin-fs = "2.3.0"
rayon = "1.10.0"
blake3 = "1.5.1"
palette = "0.7"
jpeg-decoder = "0.3.0"
wgpu = "0.19"
pollster = "0.3"
bytemuck = { version = "1.14", features = ["derive"] }
window-vibrancy = "0.6.0"
anyhow = "1.0.86"
kamadak-exif = "0.6.1"
rawler = { path = "rawler" }
serde_bytes = "0.11.17"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.8", features = ["v4", "serde"] }
walkdir = "2.5.0"
trash = "5.2.2"
imageproc = "0.25.0"
ort = { version = "1.16.3", features = ["load-dynamic"] }
ndarray = "0.15.6"
reqwest = { version = "0.12", features = ["json", "multipart"] }
tokio-tungstenite = { version = "0.23", features = ["native-tls"] }
futures-util = "0.3"
raw-window-handle = "0.6.2"
os_info = "3"
little_exif = "0.6"
chrono = "0.4"
tauri-plugin-process = "2"
tauri-plugin-os = "2.3.0"
tauri-plugin-log = "2"
tauri-plugin-devtools = "2.0.0"
log = { version = "0.4", features = ["serde"] }
env_logger = "0.11.8"

[build-dependencies]
tauri-build = { version = "2.0", features = [] }

[profile.dev]
opt-level = 3
debug = true
incremental = true

[profile.release]
codegen-units = 1
lto = true
strip = true
